version: '2.0'

services:
  couch:
    container_name: couch
    build: https://github.com/gribanov2la/docker-couchdb.git
    ports:
      - '3003:5984'
    environment:
      - COUCHDB_DBNAME=mydb
  sample-app:
    container_name: react-calculator-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_DB_URL=http://localhost:3003/mydb