export const PUSH_HISTORY_ITEMS = 'PUSH_HISTORY_ITEMS';

export const FETCH_HISTORY_ITEMS_SUCCEEDED = 'FETCH_HISTORY_ITEMS_SUCCEEDED';
export const FETCH_HISTORY_ITEMS_FAILED = 'FETCH_HISTORY_ITEMS_FAILED';
export const FETCH_HISTORY_ITEMS_REQUESTED = 'FETCH_HISTORY_ITEMS_REQUESTED';

export const PUT_HISTORY_ITEM_SUCCEEDED = 'PUT_HISTORY_ITEM_SUCCEEDED';
export const PUT_HISTORY_ITEM_FAILED = 'PUT_HISTORY_ITEM_FAILED';
export const PUT_HISTORY_ITEM_REQUESTED = 'PUT_HISTORY_ITEM_REQUESTED';